// @generated by idiolect-codegen from verify-spec/runners.json. do not edit.

//! Declarative taxonomy of verification runners. Each entry maps to a hand-written module under crates/idiolect-verify/src/<module>.rs implementing the VerificationRunner trait. The generated module in the same crate exposes a RUNNERS slice of descriptors for enumeration; runner instantiation stays caller-supplied because constructors take different configuration (corpus, budget, generator closure) per kind.

#![allow(missing_docs, clippy::doc_markdown)]

use idiolect_records::generated::verification::VerificationKind;
/// Static descriptor for a shipped verification runner.
#[derive(Debug, Clone, Copy)]
pub struct RunnerDescriptor {
    /// Kebab-case kind matching the lexicon taxonomy.
    pub kind: &'static str,
    /// Module name containing the runner impl.
    pub module: &'static str,
    /// Spec-sourced description.
    pub description: &'static str,
}
/// Every shipped verification runner's descriptor, in spec order.
pub const RUNNERS: &[RunnerDescriptor] = &[
    RunnerDescriptor {
        kind: "roundtrip-test",
        module: "roundtrip",
        description: "Apply the lens forward then backward on a caller-supplied corpus and check put(get(src)) == src for every record.",
    },
    RunnerDescriptor {
        kind: "property-test",
        module: "property_test",
        description: "Like roundtrip-test but the corpus is produced by a caller-supplied generator closure rather than a static Vec.",
    },
    RunnerDescriptor {
        kind: "static-check",
        module: "static_check",
        description: "Run panproto's schema validator on the lens's source and target schemas. Does not invoke the lens itself.",
    },
];
/// Return the `VerificationKind` values the crate has shipped runners for.
#[must_use]
pub fn runner_kinds() -> Vec<VerificationKind> {
    vec![
        VerificationKind::RoundtripTest,
        VerificationKind::PropertyTest,
        VerificationKind::StaticCheck,
    ]
}
