// @generated by idiolect-codegen from orchestrator-spec/queries.json. do not edit.

//! CLI dispatcher for `idiolect orchestrator …` subcommands.
#![allow(
    missing_docs,
    clippy::doc_markdown,
    clippy::too_many_lines,
    unused_imports
)]
use anyhow::{Result, anyhow, bail};
use std::process::ExitCode;
/// Dispatch an `idiolect orchestrator <path>` invocation.
///
/// Returns the HTTP path + query string (relative to the configured base URL).
/// The caller fetches and prints the response.
#[allow(clippy::missing_errors_doc)]
pub fn dispatch(
    path: &[&str],
    flags: &std::collections::HashMap<String, String>,
) -> Result<String> {
    match path {
        ["adapters"] => {
            if let Some(value) = flags.get("framework") {
                return Ok(format!("/v1/adapters?framework={}", urlencode(value)));
            }
            Err(anyhow!(
                "`orchestrator adapters` requires one of: --framework"
            ))
        }
        ["bounties"] => {
            if let Some(value) = flags.get("requester_did") {
                return Ok(format!(
                    "/v1/bounties/by-requester?requester_did={}",
                    urlencode(value)
                ));
            }
            Ok("/v1/bounties/open".to_owned())
        }
        ["changes"] => {
            if let Some(value) = flags.get("community_uri") {
                return Ok(format!(
                    "/v1/changes/for-community?community_uri={}",
                    urlencode(value)
                ));
            }
            Ok("/v1/changes/open".to_owned())
        }
        ["federations"] => {
            if let Some(value) = flags.get("community_uri") {
                return Ok(format!(
                    "/v1/federations/for-community?community_uri={}",
                    urlencode(value)
                ));
            }
            if let Some(value) = flags.get("peer_uri") {
                return Ok(format!(
                    "/v1/federations/for-peer?peer_uri={}",
                    urlencode(value)
                ));
            }
            Err(anyhow!(
                "`orchestrator federations` requires one of: --community_uri, --peer_uri"
            ))
        }
        ["migrations"] => {
            if let Some(value) = flags.get("change_uri") {
                return Ok(format!(
                    "/v1/migrations/for-change?change_uri={}",
                    urlencode(value)
                ));
            }
            Ok("/v1/migrations/active".to_owned())
        }
        ["recommendations"] => Ok("/v1/recommendations".to_owned()),
        ["releases"] => {
            if let Some(value) = flags.get("community_uri") {
                return Ok(format!(
                    "/v1/releases/for-community?community_uri={}",
                    urlencode(value)
                ));
            }
            Err(anyhow!(
                "`orchestrator releases` requires one of: --community_uri"
            ))
        }
        ["verifications"] => {
            if let Some(value) = flags.get("lens_uri") {
                return Ok(format!("/v1/verifications?lens_uri={}", urlencode(value)));
            }
            Err(anyhow!(
                "`orchestrator verifications` requires one of: --lens_uri"
            ))
        }
        [other, ..] => bail!("unknown orchestrator subcommand: {other}"),
        [] => bail!("`orchestrator` subcommand required"),
    }
}
/// Minimal percent-encoding for CLI flag values forwarded as
/// HTTP query parameters. Matches the hand-written helper in
/// `main.rs`.
fn urlencode(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for b in s.bytes() {
        match b {
            b'a'..=b'z' | b'A'..=b'Z' | b'0'..=b'9' | b'-' | b'_' | b'.' | b'~' => {
                out.push(b as char);
            }
            _ => {
                use std::fmt::Write;
                write!(&mut out, "%{b:02X}").expect("write to String cannot fail");
            }
        }
    }
    out
}
/// Help text for `idiolect orchestrator …` — shown by the
/// top-level `help` subcommand.
#[must_use]
pub fn help_text() -> String {
    let mut s = String::from("  orchestrator subcommands:\n");
    s.push_str(
        "    orchestrator adapters --framework VALUE   Every adapter declared for the given framework (case-insensitive).\n",
    );
    s.push_str(
        "    orchestrator bounties   Every cataloged bounty whose status is `open`, `claimed`, or unset.\n",
    );
    s.push_str(
        "    orchestrator bounties --requester_did VALUE   Every bounty authored by the given requester DID.\n",
    );
    s.push_str(
        "    orchestrator changes   Every governed change that is still in draft or review.\n",
    );
    s.push_str(
        "    orchestrator changes --community_uri VALUE   Every governed change owned by the selected community.\n",
    );
    s.push_str(
        "    orchestrator federations --community_uri VALUE   Every federation relationship declared by the selected community.\n",
    );
    s.push_str(
        "    orchestrator federations --peer_uri VALUE   Every federation relationship pointing at the selected peer community.\n",
    );
    s.push_str("    orchestrator migrations   Every planned, running, or paused migration run.\n");
    s.push_str(
        "    orchestrator migrations --change_uri VALUE   Every migration run attached to the selected governed change.\n",
    );
    s.push_str(
        "    orchestrator recommendations   Every recommendation whose lens_path is non-empty.\n",
    );
    s.push_str(
        "    orchestrator releases --community_uri VALUE   Every signed release published for the selected community.\n",
    );
    s.push_str(
        "    orchestrator verifications --lens_uri AT_URI   Every verification in the catalog that targets the given lens.\n",
    );
    s
}
