//! Panproto-native rust rendering: the generated module-index files
//! routed through `panproto-parse`'s verified tree-sitter-rust
//! emitter instead of string composition.
//!
//! This is the pilot for the swap point documented on
//! [`TargetEmitter`](crate::target::TargetEmitter): each directory
//! `mod.rs` is built as a by-construction
//! [`AbstractSchema`](panproto_schema::AbstractSchema) in the
//! tree-sitter-rust theory (vertex kinds are grammar rule names,
//! `child_of` / field edges mirror the CST, leaves carry
//! `literal-value` constraints) and rendered with
//! [`ParserRegistry::pretty_with_protocol`](panproto_parse::ParserRegistry::pretty_with_protocol).
//! Keywords and punctuation (`mod`, `;`, attribute brackets) are not
//! in the schema at all; the grammar walker reconstructs them from
//! `grammar.json`, which is the by-construction guarantee the string
//! renderer cannot offer.
//!
//! Two seams are deliberate:
//!
//! - File-level fixed bits (the `@generated` header, the
//!   `#![allow(missing_docs)]` prologue, the blank lines between
//!   them) are stitched as text, matching the convention both
//!   existing targets use. The emitter renders items, not files.
//! - A `token_tree`'s content is a single leaf carrying the raw token
//!   run. Anonymous punctuation between token siblings (the `::` in
//!   `clippy::module_inception`) has no CST vertex, so a
//!   child-per-token encoding would drop it; one leaf per token run
//!   keeps the bytes, and the brackets still come from the
//!   `token_tree` grammar rule.
//!
//! Output is normalised by the same `rustfmt` pass as the syn target,
//! and `tests/panproto_pilot_parity.rs` pins the two byte-equal. The
//! syn target stays canonical; this module proves the panproto path
//! on real output.

use std::collections::BTreeSet;

use panproto_parse::{EmitVerificationStatus, LayoutPolicy};
use panproto_schema::{AbstractSchema, Protocol, SchemaBuilder};

use crate::lexicon::{LexiconDoc, is_rust_keyword};
use crate::target::EmitError;

use super::gate::{PANPROTO_STACK_BYTES, shared_registry};
use super::rust::{directory_module_tree, rustfmt};

/// File-level fixed bits stitched around the panproto-rendered items.
const GENERATED_PROLOGUE: &str =
    "// @generated by idiolect-codegen. do not edit.\n\n#![allow(missing_docs)]\n\n";

/// Render every directory `mod.rs` through the panproto emit
/// pipeline. Same paths and (post-rustfmt) same bytes as the syn
/// target's index files.
///
/// # Errors
///
/// Returns [`EmitError::Unsupported`] when panproto does not report
/// `emit_pretty` for the rust grammar as test-verified, and
/// [`EmitError::InvalidAst`] when schema construction, rendering, or
/// the rustfmt normalisation fails.
pub fn directory_mod_files(docs: &[LexiconDoc]) -> Result<Vec<(String, String)>, EmitError> {
    // Refuse to render through an emit pipeline whose fixed-point law
    // panproto's own suite has not exercised for this grammar.
    let status = shared_registry().emit_verification_status("rust");
    if status != EmitVerificationStatus::Verified {
        return Err(EmitError::Unsupported {
            target: "rust",
            detail: format!(
                "panproto emit_pretty for the rust grammar is {status:?}, not Verified"
            ),
        });
    }

    let tree = directory_module_tree(docs);

    // The grammar walker recurses through tree-sitter production
    // trees; run the render batch on a worker with the same stack
    // reserve panproto's own rust/typescript tests use.
    std::thread::scope(|scope| {
        std::thread::Builder::new()
            .stack_size(PANPROTO_STACK_BYTES)
            .spawn_scoped(scope, move || {
                let mut files = Vec::with_capacity(tree.len());
                for (dir, children) in &tree {
                    let dir_leaf = dir.last().map(String::as_str);
                    let schema = module_index_schema(dir_leaf, children)?;
                    let bytes = shared_registry()
                        .pretty_with_protocol("rust", &schema, &LayoutPolicy::default())
                        .map_err(|e| EmitError::InvalidAst {
                            target: "rust",
                            source: Box::new(e),
                        })?;
                    let items = String::from_utf8(bytes).map_err(|e| EmitError::InvalidAst {
                        target: "rust",
                        source: Box::new(e),
                    })?;
                    let formatted = rustfmt(&format!("{GENERATED_PROLOGUE}{items}"))?;
                    files.push((format!("{}/mod.rs", dir.join("/")), formatted));
                }
                Ok(files)
            })
            .map_err(|e| EmitError::InvalidAst {
                target: "rust",
                source: Box::new(e),
            })?
            .join()
            .map_err(|_| EmitError::InvalidAst {
                target: "rust",
                source: "panproto render worker panicked".into(),
            })?
    })
}

/// Build the abstract schema for one directory index: a
/// `source_file` whose children are `pub mod <child>;` items, with an
/// `#[allow(clippy::module_inception)]` attribute item preceding any
/// child module named after its parent directory.
fn module_index_schema(
    dir_leaf: Option<&str>,
    children: &BTreeSet<String>,
) -> Result<AbstractSchema, EmitError> {
    let invalid = |e: panproto_schema::SchemaError| EmitError::InvalidAst {
        target: "rust",
        source: Box::new(e),
    };

    let protocol = Protocol {
        name: "rust".into(),
        schema_theory: "ThRust".into(),
        instance_theory: "ThRustInstance".into(),
        ..Protocol::default()
    };

    let mut b = SchemaBuilder::new(&protocol)
        .vertex("src", "source_file", None)
        .map_err(invalid)?
        .entry("src");

    for (i, child) in children.iter().enumerate() {
        // A child whose name equals its parent directory is the
        // lexicon-tree expression of an NSID like
        // `dev.panproto.schema.schema`. The compiler accepts the
        // resulting module; clippy's module_inception lint flags it,
        // so an attribute item precedes the declaration.
        if dir_leaf == Some(child.as_str()) {
            let attr_item = format!("attr{i}");
            let attr = format!("attr{i}.meta");
            let attr_path = format!("attr{i}.path");
            let attr_args = format!("attr{i}.args");
            let attr_lint = format!("attr{i}.lint");
            b = b
                .vertex(&attr_item, "attribute_item", None)
                .map_err(invalid)?
                .edge("src", &attr_item, "child_of", None)
                .map_err(invalid)?
                .vertex(&attr, "attribute", None)
                .map_err(invalid)?
                .edge(&attr_item, &attr, "child_of", None)
                .map_err(invalid)?
                .vertex(&attr_path, "identifier", None)
                .map_err(invalid)?
                .edge(&attr, &attr_path, "child_of", None)
                .map_err(invalid)?
                .constraint(&attr_path, "literal-value", "allow")
                .vertex(&attr_args, "token_tree", None)
                .map_err(invalid)?
                .edge(&attr, &attr_args, "arguments", None)
                .map_err(invalid)?
                .vertex(&attr_lint, "identifier", None)
                .map_err(invalid)?
                .edge(&attr_args, &attr_lint, "child_of", None)
                .map_err(invalid)?
                .constraint(&attr_lint, "literal-value", "clippy::module_inception");
        }

        let ident = if is_rust_keyword(child) {
            format!("r#{child}")
        } else {
            child.clone()
        };
        let item = format!("mod{i}");
        let vis = format!("mod{i}.vis");
        let name = format!("mod{i}.name");
        b = b
            .vertex(&item, "mod_item", None)
            .map_err(invalid)?
            .edge("src", &item, "child_of", None)
            .map_err(invalid)?
            .vertex(&vis, "visibility_modifier", None)
            .map_err(invalid)?
            .edge(&item, &vis, "child_of", None)
            .map_err(invalid)?
            .constraint(&vis, "literal-value", "pub")
            .vertex(&name, "identifier", None)
            .map_err(invalid)?
            .edge(&item, &name, "name", None)
            .map_err(invalid)?
            .constraint(&name, "literal-value", &ident);
    }

    b.build_abstract().map_err(invalid)
}
