// @generated by idiolect-codegen from observer-spec/methods.json. do not edit.

//! Declarative taxonomy of observation methods shipped with the observer. Each entry maps to a hand-written module under crates/idiolect-observer/src/methods/<module>.rs that implements the ObservationMethod trait. The generated module in the same crate re-exports the struct types and provides a METHODS slice + default_methods() constructor for registering the bundled set.

#![allow(missing_docs, clippy::doc_markdown)]
#![allow(unused_imports)]
/// Whether a method's `observe` receives the raw event (record-form)
/// or a panproto WInstance (instance-form).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MethodForm {
    /// `observe(&IndexerEvent)` — implements `crate::method::ObservationMethod`.
    Record,
    /// `observe(&WInstance, nsid)` — implements `crate::instance_method::InstanceMethod`.
    Instance,
}
/// Static descriptor for a bundled observation method.
#[derive(Debug, Clone, Copy)]
pub struct MethodDescriptor {
    /// Canonical method name.
    pub name: &'static str,
    /// Version string read from `<module>::METHOD_VERSION`.
    pub version: &'static str,
    /// Spec-sourced description.
    pub description: &'static str,
    /// Which trait the method implements.
    pub form: MethodForm,
}
/// Every bundled observation method's descriptor, in spec order.
pub const METHODS: &[MethodDescriptor] = &[
    MethodDescriptor {
        name: crate::methods::correction_rate::METHOD_NAME,
        version: crate::methods::correction_rate::METHOD_VERSION,
        description: "Per-lens correction counts grouped by reason. Signals translation-quality rumor.",
        form: MethodForm::Record,
    },
    MethodDescriptor {
        name: crate::methods::encounter_throughput::METHOD_NAME,
        version: crate::methods::encounter_throughput::METHOD_VERSION,
        description: "Encounter traffic by kind and downstream result. Signals firehose liveness.",
        form: MethodForm::Record,
    },
    MethodDescriptor {
        name: crate::methods::verification_coverage::METHOD_NAME,
        version: crate::methods::verification_coverage::METHOD_VERSION,
        description: "Per-lens verification counts by kind, result, and distinct verifiers. Signals formal-channel evidence.",
        form: MethodForm::Record,
    },
    MethodDescriptor {
        name: crate::methods::lens_adoption::METHOD_NAME,
        version: crate::methods::lens_adoption::METHOD_VERSION,
        description: "Per-lens encounter count and distinct-invoker DIDs. Signals adoption breadth.",
        form: MethodForm::Record,
    },
];
/// Fresh instances of every bundled record-form method, in spec order.
///
/// Instance-form methods are not included — they need a caller-supplied
/// schema resolver passed to
/// [`crate::instance_method::InstanceMethodAdapter`]. See [`METHODS`]
/// for their descriptors.
#[must_use]
pub fn default_methods() -> Vec<Box<dyn crate::method::ObservationMethod>> {
    vec![
        Box::new(crate::methods::correction_rate::CorrectionRateMethod::new()),
        Box::new(crate::methods::encounter_throughput::EncounterThroughputMethod::new()),
        Box::new(crate::methods::verification_coverage::VerificationCoverageMethod::new()),
        Box::new(crate::methods::lens_adoption::LensAdoptionMethod::new()),
    ]
}
