#!/usr/bin/env bun
// Stage the workspace-root `lexicons/` tree alongside the package
// in two forms:
//
// 1. `packages/schema/lexicons/` — file-tree copy. Used by Node
//    consumers via `loadLexiconDocs()`, which reads from disk;
//    also what npm ships in the published tarball.
// 2. `packages/schema/src/generated-lexicons.ts` — inline-as-JS
//    constant. Used by browser consumers via the `bundledLexiconDocs`
//    export, baked into `dist/index.js` by the bundler. No `node:fs`
//    at consumer-runtime; works everywhere.
//
// Idempotent. Both targets are gitignored; the workspace root is
// the source of truth.
//
// Run as `bun run copy-lexicons` (also auto-runs as `pretest`)
// or via `bun run build`.

import { cpSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = fileURLToPath(new URL(".", import.meta.url));
const ROOT = resolve(HERE, "..");
const WORKSPACE_LEXICONS = resolve(ROOT, "..", "..", "lexicons");
const LOCAL_LEXICONS = resolve(ROOT, "lexicons");
const GENERATED_TS = resolve(ROOT, "src", "generated-lexicons.ts");

// step 1: tree copy.
rmSync(LOCAL_LEXICONS, { recursive: true, force: true });
cpSync(WORKSPACE_LEXICONS, LOCAL_LEXICONS, { recursive: true });

// step 2: inline the JSON docs into a generated TS module.
function collectJsonFiles(root: string): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(root)) {
    const path = join(root, entry);
    const stat = statSync(path);
    if (stat.isDirectory()) {
      out.push(...collectJsonFiles(path));
    } else if (stat.isFile() && path.endsWith(".json")) {
      out.push(path);
    }
  }
  return out;
}

const docs = collectJsonFiles(WORKSPACE_LEXICONS)
  .map((path) => JSON.parse(readFileSync(path, "utf8")) as Record<string, unknown>)
  .filter((doc) => doc["lexicon"] === 1 && typeof doc["id"] === "string")
  .sort((a, b) => String(a["id"]).localeCompare(String(b["id"])));

const banner = `// @generated by scripts/copy-lexicons.ts. Do not edit by hand.\n//\n// Inline copy of every lexicon document under the workspace-root\n// \`lexicons/\` tree, baked in as a plain ES module export so browser\n// consumers can use \`bundledLexiconDocs\` without \`node:fs\`.\n\nimport type { LexiconDoc } from "@atproto/lexicon";\n\n`;

writeFileSync(
  GENERATED_TS,
  `${banner}export const bundledLexiconDocs: LexiconDoc[] = ${JSON.stringify(docs, null, 2)} as LexiconDoc[];\n`,
);
